branches:
  only:
    - master

os: osx
osx_image: xcode10.1
language: swift

env:
  global:
    - XCODE_PROJECT="Xcode/FFFoundation.xcodeproj"
    - XCODE_SCHEME=FFFoundation
script: ./scripts/build_xcode.sh

jobs:
  include:
    - name: "iOS Xcode"
      env: XCODE_DESTINATION="platform=iOS Simulator,OS=12.1,name=iPad Pro (9.7-inch)"
    - name: "macOS Xcode"
      env: XCODE_DESTINATION="platform=macOS"
    - name: "macOS SwiftPM"
      before_script: swift package clean
      script: swift test
    - name: "Linux SwiftPM"
      os: linux
      distro: xenial
      language: generic
      sudo: required
      services:
        - docker
      install: docker pull swift:4.2
      before_script: ./scripts/run_on_linux.sh '4.2' 'swift package clean'
      script: ./scripts/run_on_linux.sh '4.2' 'swift test'
