branches:
  only:
    - master
    - develop
language: swift
os: osx
osx_image: xcode10
xcode_project: Xcode/FFFoundation.xcodeproj
xcode_scheme: FFFoundation
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPad Pro (9.7-inch)
